begin;

create table if not exists thoughts (
  id integer primary key generated by default as identity,
  user_id varchar(36) not null,
  content text not null,
  created_at timestamp default now() not null
);

commit;